version: '3.7'

services:

    web:
        container_name: elearning-api
        build:
            context: .
            dockerfile: Dockerfile
            target: dev-publish
        ports:
            - 5000:80
        depends_on:
            - mysql
        environment:
            - MYSQL_CONNECTION_STRING="server=mysql.local;database=elearning;user=root;password=CraftCode2023"
            - ASPNETCORE_ENVIRONMENT="Development"

        networks:
            elearning-network:
                aliases:
                    - elearning-api.local

    mysql:
        container_name: elearning-database
        image: mysql:8.0.23
        ports:
            - 5006:3306
        environment:
            - MYSQL_DATABASE=elearning
            - MYSQL_ROOT_USER=root
            - MYSQL_PASSWORD=CraftCode2023
            - MYSQL_ROOT_PASSWORD=CraftCode2023

        volumes:
            - db_data:/db_data
        networks:
            elearning-network:
                aliases:
                    - mysql.local

volumes:
    db_data:

networks:
    elearning-network:
        # external: true