name: testing

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  testing:

    runs-on: ubuntu-latest

    defaults:
     run:
      working-directory: ./elearning

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 2.1.x
        
    - name: List directories
      run: ls -ll
    - name: Restore dependencies
      run: dotnet restore elearning.sln
    - name: Build
      run: dotnet build elearning.sln --no-restore
    - name: Test
      working-directory: ./elearning
      run: dotnet test --no-build --verbosity normal
